version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    tty: true
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - redis
    ports:
      - "${PORT}:${PORT}"
    environment:
      TZ: "Asia/Tokyo"

  redis:
    image: "redis:latest"
    volumes:
      - redis-data:/data
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

volumes:
  redis-data:
    driver: local