version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    tty: true
    volumes:
      - ./:/usr/src/app
      - /app/node_modules
    ports:
      - "${PORT}:${PORT}"
    environment:
      TZ: "Asia/Tokyo"